### ISSUE TITLE
how to install Ebook converter？

### ISSUE THREAD

**Issue by VMRx5MYRJka5yQY** [YunoHost-Apps/calibreweb_ynh#107]
I need to convert the book format, but the app doesn't have it, how can I add it?

**Comment by Krakinou** [comment]
Hello
You have to enter the path to the converter binary into Calibre-Web -> Admin -> Basic Configuration -> External binaries.
I'm not using it, so I'm not very sure, but I think you may find more info on the upstream repo.
For example : https://github.com/janeczku/calibre-web/issues/624

 My understanding is that if you run calibre-web on a server on which Calibre is installed, the Calibre converter may be used.

**Comment by richie80** [comment]
Here is info from linuxserver: 
64bit only We have implemented the optional ability to pull in the dependencies to enable ebook conversion utilising Calibre, this means if you don't require this feature the container isn't uneccessarily bloated but should you require it, it is easily available. This optional layer will be rebuilt automatically on our CI pipeline upon new Calibre releases so you can stay up to date. 
To use this option **add the optional environmental variable as shown in the docker-mods section** to pull an addition docker layer to enable ebook conversion and then in the Calibre-Web admin page **(Basic Configuration:External Binaries**) set the Path to Calibre E-Book Converter to /usr/bin/ebook-convert on versions 0.6.21 and lower. **For 0.6.22 and higher, set the directory, /usr/bin/ only.**

This image contains the [kepubify](https://pgaskin.net/kepubify/) ebook conversion tool (MIT License) to convert epub to kepub. In the Calibre-Web admin page (Basic Configuration:External Binaries) set the Path to Kepubify E-Book Converter to /usr/bin/kepubify

https://docs.linuxserver.io/images/docker-calibre-web/#application-setup

**Comment by Krakinou** [comment]
Note that the kepubify binary is now directly included in the package since a few version.
