### ISSUE TITLE
How to get OPDS working

### ISSUE THREAD

**Issue by Galunid** [YunoHost-Apps/calibreweb_ynh#21]
You can get OPDS working by either:
* Using your yunohost login and password "admin123"
* Changing your user password in the calibre-web panel

**Comment by Krakinou** [comment]
Hello,
I'm unclear: is this a feedback or a question?

**Comment by Galunid** [comment]
Hi, it is a feedback. After doing what I described above, OBDs starts working

**Comment by Krakinou** [comment]
OK thanks :)
I just start working on 0.6.2 and I plan to solve this issue as well: In fact the OPDS authentication is based on Basic Http authentication, while the change I made on the calibre-web code to integrate LDAP are only for the login/logout. That's why reauthenticating using the "standard' method works.

**Comment by nwallace** [comment]
Hi -
I can't get OPDS working. I'm on version 0.96.0~ynh3, and the app is installed at the root of a subdomain of mine (let's say sub.base.tld). The regular web interface works - I can log in, upload books, read books, etc just fine.

I couldn't get my mobile apps to connect to OPDS, so I tried from a web browser to see what was going on. When I visit https://sub.base.tld/opds in a browser, if I'm not logged into Yunohost, then I am redirected to the Yunohost SSO. After I log in, or if I am already logged into Yunohost, I get a HTTP Basic Auth prompt from my browser. I have tried every combination of username and password that makes sense (my Yunohost username/password & email/password, and my CalibreWeb username/password & email/password), but no matter what I type, the prompt disappears for a second then reappears. If I click cancel, I get a 401 page, saying:

> Could not verify your access level for that URL. You have to login with proper credentials

It seems like the LDAP login stuff is breaking the OPDS authentication. Is there anything I can do to fix this?

As always, thanks a ton for the packaging! I love Yunohost and this app is great :)

**Comment by Krakinou** [comment]
Hello,
OPDS is still not available in the packaging.
LDAP authentication is currently added via a quick fix in the app packaging and this does not support OPDS.
LDAP is being currently implemented in the original Calibre-web source code and as soon as this is release, I will repackage it for Yunohost. However, I don't have any timeline so far.

Thanks :)

**Comment by nwallace** [comment]
Oh, okay thanks for the clarification! I was just confused and thought it should be working

**Comment by Krakinou** [comment]
Hello
OPDS should now be working following #35 (at least, it is for me testing with eBook-droid)
You need to set the app as public though and you may have to activate anonym browsing depending on you OPDS reader.
Can you confirm it is working for you?

**Comment by sammcf** [comment]
I have gotten it working as follows:

1: calibre-web app must be visible to visitors in yunohost groups configuration.
2: anonymous browsing must be enabled in calibre-web settings.
3: it takes a while for new user LDAP accounts to propagate across from yunohost to calibre-web, and authentication is unpredictable until this happens.
4: I have tried the following mobile apps with results:
- kybook2/3 on iOS - 100% working
- fbreader on Android - 100% working EXCEPT no covers are visible
- aldiko classic & aldiko on Android - 100% working EXCEPT no covers are visible
- moon+ reader on Android - not working. Able to connect the catalogue, but browsing any listings shows the attached error. The "recently added" selection works, but clicking on any titles displays "Unauthorized." The top rated selection works 100% fine, including covers. 

![Screenshot_20200619-212428](https://user-images.githubusercontent.com/3764388/85127888-a0624780-b273-11ea-94dc-4d0515fdd9b5.png)

**Comment by Krakinou** [comment]
Hi,
I just released the app including 0.6.8 upstream which include some corrections for OPDS.
It's working for me on moon+reader on Android.
Closing the issue as this is more related to bug in the upstream app than on the package.
You may create issues directly on the [calibre-web issue log](https://github.com/janeczku/calibre-web/issues) if you have any other problem.
