### ISSUE TITLE
Many book covers do not display in Calibreweb but work in Calibre

### ISSUE THREAD

**Issue by tootbrute** [YunoHost-Apps/calibreweb_ynh#22]
1. Awesome app! So useful.
2. Most of my book covers aren't displaying in CalibreWeb but they work in Calibre.

-I installed app through Yunohost
-Then copied my files from my Nextcloud folder into the folder /home/yunohost.multimedia/[username]/eBook
-i keep it updated with rsync

Question:
Do I need to prepare the Calibre database in some way to work with Calibreweb?
Have others experience this?

![calibre_Screenshot](https://user-images.githubusercontent.com/47593393/56270080-e4b1ff00-6127-11e9-8050-716f144d4a58.png)
![calibre-web-screenshot](https://user-images.githubusercontent.com/47593393/56270086-ea0f4980-6127-11e9-9c8d-70766069001e.png)

**Comment by Krakinou** [comment]
1. Thanks, but I'm just the packager, the real work is [here](https://github.com/janeczku/calibre-web) :)
2. I'm not aware of any issue regarding book cover, but maybe give a look to the issue log of the calibre-web repo. Is there anything in `/var/log/calibreweb/calibreweb.log`?

Regarding the sync with nextcloud, you may directly 
1. either change the calibreweb setting to aim at the nextcloud directory you're using as your library
2. or directly use the ` /home/yunohost.multimedia/[username]/eBook` folder as your main calibre directory, as it is directly inside nextcloud (at least if you're using the Yunohost Nextcloud app)
Just be aware that in both case you should not upload data from calibreweb as it will not be correctly synced in the nextcloud directory, I'm currently working on it an dI hope to issue a patch soon.

Calibreweb directly use the metadata.db database from the calibre directory, you do not need to make any settings. In the app initial install, I set up an empty database if the ebook directory is empty.

**Comment by tootbrute** [comment]
Oh ok i understand.
so i think i understood the limitation about using Nextcloud.

so you CAN store your files in Nextcloud BUT you can't add books from calibre-web into the library.

If that's true, that's fine with me. I only want to add books with Calibre, then story on nextcloud, and view on Calibre-web. Also if it's true, I think you should rewrite the description, it isn't as clear as you just made it.

I'll go check out the other github place.

Thanks for your thoughts!

**Comment by Krakinou** [comment]
To be 100% clear: 
- you may not use an internal nextcloud directory, as nextcloud does not like that we change files inside its folder directly, you have to scan it back afterward for it to take notice of the change. 
- You may use the ebook directory, which is an external directory for nextcloud, the only limitation so far is that nextcloud will not take it into account until you open the folder in the web interface (or that you scan it), hence some risks of data corruption if you simultaneously update data through calibre.
I'm looking for a way to update nextcloud database immediately after a book upload.

**Comment by Krakinou** [comment]
Does the update to 0.6.7 solve the cover issue?

**Comment by tootbrute** [comment]
> Does the update to 0.6.7 solve the cover issue?

yes the covers load much faster, and they all load. THANK YOU!

**Comment by Krakinou** [comment]
Cool!
Thanks for the feedback!
