### ISSUE TITLE
Switch "public" setting after install

### ISSUE THREAD

**Issue by ahstro** [YunoHost-Apps/calibreweb_ynh#23]
I made [an issue](https://github.com/YunoHost/issues/issues/1378) over at the official YunoHost issue tracker and they directed me here. It'd be nice if the ability to make Calibre-Web a public app after installing it as private, if that's possible? Also, is there a way to do that manually now? Thanks! :relaxed:

**Comment by Krakinou** [comment]
Hello,
Sure, just follow the steps on this [thread](https://forum.yunohost.org/t/dokuwiki-de-prive-a-public/7113/2).
Change 'Docuwiki' with 'calibreweb' and it shoudl work.

Then just check where is your library, as per default if the app is public, the library is placed into 'shared' multimedia directory while usually, if you set it on private you want to have it on your own multimedia directory.
Anyway, both will work, it just depend if you want to share the library or not.
