### ISSUE TITLE
Error 500: Internal server error when browsing

### ISSUE THREAD

**Issue by SpencerDub** [YunoHost-Apps/calibreweb_ynh#28]
I just installed this app on my YunoHost server and have begun uploading ebook files.

When I click "Categories," "Series," "Authors", "Publishers", or "Languages" in the Browsing sidebar, I get directed to an error page:

> **Internal Server Error**
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

The corresponding log entries in `/var/log/calibreweb/calibreweb.log` look like this:

>CompileError: Can't resolve label reference for ORDER BY / GROUP BY / DISTINCT etc. Textual SQL expression 'books_publishers_link.pub...' should be explicitly declared as text('books_publishers_link.pub...')
>127.0.0.1 - - [2019-12-27 19:01:31] "GET /calibre/publisher HTTP/1.0" 500 444 0.010349

How can I troubleshoot and fix this?

Thanks.

**Comment by Krakinou** [comment]
Hmmm
This seems more like an issue from the application itself.
I would recommend open an issue [here](https://github.com/janeczku/calibre-web/issues) if there is not one already

**Comment by SpencerDub** [comment]
Thanks, @Krakinou. I investigated and it looked like this issue was [brought up](https://github.com/janeczku/calibre-web/issues/835) and [fixed in the source](https://github.com/janeczku/calibre-web/commit/5b0a0e21391b221f1f6377a66de7da5ced3603c9) back in March 2019. The fix in the original application appears to be newer than the latest version of CalibreWeb_ynh.

**Comment by SpencerDub** [comment]
Updating the application via the admin panel to v0.6.4 indeed fixed this issue.
