### ISSUE TITLE
YunoHost logo covers text

### ISSUE THREAD

**Issue by wakest** [YunoHost-Apps/calibreweb_ynh#29]
the YunoHost logo should definitely not be on the reading interface of Calibre-web

![image](https://user-images.githubusercontent.com/7890201/73266549-ec5d0480-418b-11ea-8c09-a8c6672e8dd4.png)

**Comment by Krakinou** [comment]
Hello,
This is not linked to calibreweb but to yunohost : It is used to go back to yunohost dashboard.
You may move and resize the logo with your mouse so that it stand anywhere you pleased with on the page.
