### ISSUE TITLE
version mismatch 

### ISSUE THREAD

**Issue by siwinter** [YunoHost-Apps/calibreweb_ynh#32]
Thanks for the great tool. I now use the server more often than the original calibre app.
Unfortunately, the installation script is not currently producing a functioning server.
Clicking on ebook covers or sorting buttons (author, language, etc) is ignored or leads to an error page.
The reason is that the installed version of calibreweb (0.6.0) does not match the versions of dependent packages (Werkzeug, sqlalchemy).
I expanded a patch file in this [fork](https://github.com/siwinter/calibreweb_ynh) and opened a pull request to fix the issue.
This is probably not a definitive solution, but it works for me.

**Comment by Krakinou** [comment]
Hello,
Sorry I wasn't aware of this issue.
I just started working on [0.6.6 integration](https://github.com/YunoHost-Apps/calibreweb_ynh/tree/develop-6.6) this week.
This version will use python3.5, have up to date dependencies and will hopefully have a more "standard" integration in yunohost  LDAP.
As I plan to release it in a few weeks if everything is ok, I rather work on the 0.6.6 integration than testing the backport (which will surely leads to some regression on some installs).
Nevertheless, thanks for your help and feel free to contribute to the 0.6.6.

**Comment by Krakinou** [comment]
Closed with #35
