### ISSUE TITLE
Consider renaming the repo to `calibreweb_ynh` for consistency

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/calibreweb_ynh#5]
Hellow !

If you have some time, please consider renaming this repo to `calibreweb_ynh` instead of `calibre_ynh` so that it's consistent with the `id` field in `manifest.json` !

(Github should take care of automatically redirecting old references to the previous name ... at least for some time)

**Comment by Krakinou** [comment]
Well, that would be a great pleasure to ensure consistency, but it seems that since I moved it to Yunohost-Apps org, I cannot change it anymore: the settings tab has disappeared?

**Comment by Krakinou** [comment]
Hey Alex,
Now that you can change repo name, could you change this one too?

**Comment by alexAubin** [comment]
Indeed ! That's done ! Thanks :stuck_out_tongue:
