### ISSUE TITLE
Can't access calibreweb; logs show webserver has stopped

### ISSUE THREAD

**Issue by SpencerDub** [YunoHost-Apps/calibreweb_ynh#50]
I have installed calibreweb on my YunoHost instance at mydomain.com/calibre/. I used to be able to access it by going to that URL or clicking the link in the YunoHost dashboard.

Now, when I try, I get a `502 Bad Gateway` error and my Nginx error logs show a corresponding `111: Connection Refused` error:

> 2020/08/10 19:31:31 [error] 31431#31431: *287 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.179, server: mydomain.com, request “GET /calibre/ HTTP/1.0”, upstream: “http://127.0.0.1:8083/calibre/”, host: “mydomain.com”

Looking at `/var/log/calibreweb/calibreweb.log`, I see this:

```
[2020-08-10 15:36:56,095]  INFO {cps:88} Starting Calibre Web...
[2020-08-10 15:36:56,372]  INFO {cps.server:152} Starting Tornado server on :8083
[2020-08-10 15:37:21,914]  INFO {cps.server:200} webserver stop (restart=False)
[2020-08-10 15:37:21,914]  INFO {cps.server:200} webserver stop (restart=False)
[2020-08-10 15:37:21,916]  INFO {cps.server:180} Performing shutdown of Calibre-Web
[2020-08-10 15:39:27,640]  INFO {cps.server:207} webserver stop (restart=False)
[2020-08-10 15:39:27,638]  INFO {cps.server:207} webserver stop (restart=False)
[2020-08-11 10:25:25,289]  INFO {cps.server:207} webserver stop (restart=False)
[2020-08-11 10:25:25,287]  INFO {cps.server:207} webserver stop (restart=False)
```

`sudo systemctl status calibreweb` reports that calibreweb is running.

I don't know if the 502 Bad Gateway/111 Connection Refused errors I'm encountering are a problem with YunoHost, calibreweb, Nginx, or a combination of the three, so I'm asking around to try to better understand what's going on.

Should calibreweb be reporting so many `webserver stop (restart=False)` messages? Could this be related to the 502 Bad Gateway/111 Connection Refused?

Any help (within the scope of this project, of course) would be appreciated. Thanks.

**Comment by Krakinou** [comment]
Hi,
When installing/upgrading calibreweb, the server may be start/stop a few times, while not always captured in the logs, so based on the date and time of your log, this may be the issue.

When starting the service on small device, like raspberry, it may take as long as 30 second before calibreweb is available.

You may also have a look at /var/log/calibreweb/calibreweb-access.log that may give you additional information

**Comment by SpencerDub** [comment]
@Krakinou 
Thanks for the information. It seems like I don't need to worry about the `webserver stop` messages.

I checked out `/var/log/calibreweb/calibreweb-access.log` like you suggested, but there have been no entries for two months.

It seems as though something's wrong with the YunoHost/calibreweb connection, because when YunoHost attempts to retrieve calibreweb (at 127.0.0.1:8083), I get this Connection Refused error. Additionally, when I SSH into the server and run `curl 127.0.0.1:8083`, I get the response:

> curl: (7) Failed to connect to 127.0.0.1 port 8083: Connection refused

Any idea what could be going on between YunoHost and calibreweb to cause these Connection Refused errors, and how I might fix it?

**Comment by Krakinou** [comment]
Are you on the last version of the yunohost package?
Could you check if the port 8083 is open with `yunohost firewall list `?
What are the status when you run `systemctl status calibreweb`?
Did you already try of restarting both calibreweb and nginx services?
Do you have multiple instances installed?
Did you do anything special before it stop working? (Update, configuration change...)

**Comment by SpencerDub** [comment]
> Are you on the last version of the yunohost package?

Yes, I'm currently using YunoHost 3.8.5.7. I haven't yet migrated to Debian Buster.

> Could you check if the port 8083 is open...?

It is. Port 8083 is included in the list when I run that command.

> What are the status when you run `systemctl status calibreweb`?

Loaded and running, with a green dot.

> Did you already try of restarting both calibreweb and nginx services?

Yes.

> Do you have multiple instances installed?

I do not have multiple instances of calibrweb installed.

> Did you do anything special before it stop working? (Update, configuration change...)

The access log shows no new entries after June 11, the day that I configured a reverse proxy.

Traffic for my network looks like this:

```
Internet -> Router -> Raspberry Pi reverse proxy -> YunoHost server
```

The Raspberry Pi reverse proxy uses a `.conf` file for the domain. I've put the contents of that file [in a pastebin here](https://pastebin.com/jgejPeLV).

I should note, this `.conf` file applies to my entire `mydomain.com` domain; calibreweb is only one of many apps installed on that domain. Other apps are working as expected.

**Comment by Krakinou** [comment]
Well, `Connection refused while connecting to upstream client` is usually a nginx issue, so I guess there is something wrong in the reverse proxy. 
I never used one so I cannot really help you with this, however there is a setting in calibreweb regarding reverse proxy which ask for the reverse proxy header : maybe you should give it a look?

**Comment by SpencerDub** [comment]
I uninstalled and reinstalled calibreweb. That resolved it. No idea what was going on, but whatever, it's fixed!
