### ISSUE TITLE
Cannot replace covers for existing books

### ISSUE THREAD

**Issue by SpencerDub** [YunoHost-Apps/calibreweb_ynh#51]
**Issue summary**
When editing the metadata for an existing ebook in my library, if I specify a new cover image (either by URL or by upload) and hit "Save", the cover is not preserved. Other metadata updates are properly written.

**System details**
* YunoHost version: 4.0.4
* Calibreweb version: 0.96.8~ynh5

**Steps to replicate**
1. Log in to Calibreweb with an account that has edit privileges. Click an existing ebook in the library. It does not matter if the book has a cover image.
2. Click the "Edit Metadata" button.
3. Add a line of dummy text to the book synopsis.
4. Choose a new cover image for the book, either by uploading it or by specifying a URL.
5. Click "Save".
6. Look at the book detail page for the book just edited.

**Expected behavior**
The new cover is reflected on the book detail page, as is the edit to the synopsis.

**Actual behavior**
Only the edit to the synopsis is reflected. The new cover is not displayed.

**What I've checked**
* The account I'm using *does* have edit, delete, upload, and download privileges. (It's an admin account; it has all privileges.)
* *Sometimes,* clicking "Reconnect Calibre database* in the settings causes the chosen cover images to appear. It's not consistent, however.

**Comment by SpencerDub** [comment]
It may have been a caching issue. I'll check that in the future.

Thanks, @Krakinou.

**Comment by TheNomad11** [comment]
Same here. When I used a different browser, the cover image showed up

**Comment by Krakinou** [comment]
may be related to this (limitation)(https://github.com/janeczku/calibre-web/wiki/FAQ#what-to-do-if-cover-pictures-are-not-extracted-from-pdf-files)

**Comment by OzzieIsaacs** [comment]
I think this is this: 
Browser caching problem on cover change solved (I can‘t find the original issue right now)

https://github.com/janeczku/calibre-web/releases/tag/0.6.10

I fixed it with version 0.6.10 on january 17th 2021
