### ISSUE TITLE
update fails

### ISSUE THREAD

**Issue by brimwats** [YunoHost-Apps/calibreweb_ynh#53]
here are the update logs: https://paste.yunohost.org/raw/emifuxuyoy

**Comment by Krakinou** [comment]
Hi
Very strange indeed: it's as if the app had no library folder set up? Is the app functional?
Could you give me the output of the two following commands:
````
sqlite3 /var/www/calibreweb/app.db 'SELECT config_calibre_dir FROM settings WHERE ID=1'

yunohost app setting calibreweb calibre_dir
````

**Comment by brimwats** [comment]
I think it's related to an issue I had with trying to make NC access files on /var and I deleted other storage folders. I decided I don't need calibre so I uninstalled for now, will close issue.
