### ISSUE TITLE
Version is 0.96.9~ynh5 instead of 0.96.9~ynh1

### ISSUE THREAD

**Issue by supermamie** [YunoHost-Apps/calibreweb_ynh#55]
Just a really small issue, the last upgrade was from `0.96.8~ynh5` to `0.96.9~ynh5`
It should be from `0.96.8~ynh5` to `0.96.9~ynh1` as this is the 1st version using `0.96.9`

Note : as some people have already upgraded, do not do it now, but for next version upgrade.

**Comment by Krakinou** [comment]
corrected with 0.93.10~ynh1
