### ISSUE TITLE
Use Gevent instead of Tornado (Optional Dependencies)

### ISSUE THREAD

**Issue by psharma04** [YunoHost-Apps/calibreweb_ynh#56]
By installing Gevent instead of Tornado, the 200mb file size limit for calibre-web will be surpassed.

https://github.com/janeczku/calibre-web/wiki/FAQ#what-is-the-maximum-file-size-which-can-be-uploaded-through-calibre-web

**Comment by Krakinou** [comment]
Yep, I already noticed: This is also more efficient on small devices like raspberry and so on. In my case for example I cannot read comics with calibreweb on the tornado server and have to switch to Gevent.
I planned to change it for the next upstream upgrade.

**Comment by psharma04** [comment]
For my use case, I upload a lot of textbooks to my instance. A 200mb textbook is rare, so I usually need to split the file into chapters, which is just messy and annoying.

**Comment by Krakinou** [comment]
You may manually change calibreweb to gevent with following commands:
```
cd /var/www/calibreweb
echo 'gevent>=1.2.1,<20.6.0' >> ./req
pip3 install --target vendor -r req --upgrade
systemctl restart calibreweb
```
Then you will have to edit the nginx conf file to overcome the 200M limit :
````
sudo nano /etc/nginx/conf.d/yourdomainname.d/calibreweb.conf
````
And restart nginx:
````
sudo systemctl restart nginx
````
This should set calibreweb to use gevent until the next update.

**Comment by Krakinou** [comment]
Gevent is now used with 0.6.10
