### ISSUE TITLE
How to import users from yunohost?

### ISSUE THREAD

**Issue by kuba-orlik** [YunoHost-Apps/calibreweb_ynh#57]
When pressing "Import LDAP users" in admin panel, I get a message:

```
Error: No user returned in response of LDAP server
```

The README mentions that 

> Users will be synchronized with authorized Yunohost users (having the calibreweb.main authorization group) automatically. In case of issue you may force the sync in the app itself.

But I'm not sure how to add `calibreweb.main` authorization group. How do I do that?

**Comment by Krakinou** [comment]
Hi,
In yunohost config panel, go to "users/manage group and authorizations" (translated from french, so maybe the wording is a little different)
Users with the calibreweb authorization are the one that will be synchronized.

Maybe I should rework the readme so it's a little clearer...

**Comment by kuba-orlik** [comment]
Thank you for your response. That's what I assumed, but after adding the `calibre-web` permission to some users and importing them with "Import LDAP users" I get an error saying:

> Error: No user returned in response of LDAP server

**Comment by Krakinou** [comment]
Hi,
Currently working on 0.6.10 where a lot have changed regarding LDAP management. Should be available in a few days
If the issue is still there afterward, we will look deeper into it

**Comment by Krakinou** [comment]
0.6.10 is now published.
Can you confirm if the issue still occurs?

**Comment by dmogle** [comment]
I am experiencing this same problem. I'm on # version 0.96.10~ynh1. I tried adding a new user in ynh and granting them calibre-web and then running "Import LDAP Users" in calibre-web. I get the same error.

**Comment by Krakinou** [comment]
Hmmm, I think I spotted it : can you confirm you use "per user" permission and not a "all user" permission?

**Comment by dmogle** [comment]
Aha, yes. I granted permission to the All Users group and now the import works!

**Comment by PirxGR** [comment]
Same here.
YNH 4.1.8, Calibre 0.96.11~ynh1
![calibre-web-1](https://user-images.githubusercontent.com/33618992/116428572-55c33b80-a845-11eb-9fb4-fd46282d604b.png)
I am lost.

**Comment by Thovi98** [comment]
Same with latest version of Yunohost and Calibreweb (0.96.12~ynh1). I’ve set permission for all users, so I don’t know how to solve this.

**Comment by Krakinou** [comment]
Hi there,
Finally got time to work on it : This is a mistake in the default configuration of the LDAP settings in calibre-web:
You have to edit the field "LDAP Group Name" in "Basic Configuration/Feature Configuration".

In there, change the value from ````(&(objectClass=posixGroup)(permission=cn=%s.main,ou=permission,dc=yunohost,dc=org))```` to ````(&(objectClass=posixGroup)(cn=%s.main))```` : 
![image](https://user-images.githubusercontent.com/9308214/126877216-62755eb4-c9ab-47f7-904c-090d9f84e498.png)

After that, save your settings. Calibre-web will restart and you should be able to import user from visitor, custom and individual groups.
This will be solved in the next release.

**Comment by Thovi98** [comment]
Yes, it works great now ! Thank you @Krakinou :)
