### ISSUE TITLE
PDF blank cover, why doesn't automatically gets cover?? (OK with ePub)

### ISSUE THREAD

**Issue by girowue** [YunoHost-Apps/calibreweb_ynh#63]
Hi!

I have Calibre desktop, and when I sync a PDF book, the app automatically gets the cover from the first page. Why does calibre-web doesn't do that? Do I have to configure it somewhere? 

With ePub files the covers are used perfectly without any interaction. 

Thanks!

**Comment by Krakinou** [comment]
Was link to this [issue](https://github.com/janeczku/calibre-web/wiki/FAQ#what-to-do-if-cover-pictures-are-not-extracted-from-pdf-files)
Should be ok now with the last update
