### ISSUE TITLE
"German is not a valid language" - Language selection only in Chinese

### ISSUE THREAD

**Issue by TheNomad11** [YunoHost-Apps/calibreweb_ynh#65]
This might be a solved upstream issue. When I try to add the language for the uploaded book, and I type "German", an error message appears: German is not a valid language. 

This issue should have been fixed upstream in version 0.6.9, but Yunohost uses 0.6.10, so this error is not supposed to happen. On the other side, if I add German followed by a comma, I get lots of Chinese characters. And when I look at the metadata of my other previously added books, I only see Chinese characters. This might point to a bug fixed in version 0.6.11: "Chinese character language texts are no longer shown for english locale" 
https://github.com/janeczku/calibre-web/issues/1819
https://github.com/janeczku/calibre-web/releases

**Comment by Krakinou** [comment]
I just pushed 0.6.11.
Is your issue still there?

**Comment by TheNomad11** [comment]
Thanks so much, issue solved, working fine now!
