### ISSUE TITLE
Server Error after installation

### ISSUE THREAD

**Issue by vip3r78** [YunoHost-Apps/calibreweb_ynh#66]
Hello,
after installation i get an Server 500 error.
`Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/var/www/calibreweb/vendor/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/var/www/calibreweb/vendor/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/var/www/calibreweb/vendor/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/var/www/calibreweb/vendor/flask/_compat.py", line 39, in reraise
raise value
File "/var/www/calibreweb/vendor/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/var/www/calibreweb/vendor/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/var/www/calibreweb/cps/usermanagement.py", line 38, in decorated_view
return login_required(func)(*args, **kwargs)
File "/var/www/calibreweb/vendor/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/var/www/calibreweb/cps/web.py", line 718, in index
return render_books_list("newest", sort_param, 1, page)
File "/var/www/calibreweb/cps/web.py", line 421, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order)
File "/var/www/calibreweb/cps/db.py", line 608, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, pagesize, database, db_filter, order, False, *join)
File "/var/www/calibreweb/cps/db.py", line 622, in fill_indexpage_with_archived_books
.join(*join, isouter=True) \
TypeError: join() missing 1 required positional argument: 'target'`

First i´ve tried an installation on an raspberry pi 3b, then i get the same error. Now i try it on an thinclient and get this error. What ca i do?

**Comment by Krakinou** [comment]
Hi,
Very strange indeed.
Do you have the installation log? They should be available in the yunohost admin page.


-------- Message d'origine --------
De : vip3r78 ***@***.***>
Date : 23/03/2021 18:26 (GMT+01:00)
À : YunoHost-Apps/calibreweb_ynh ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [YunoHost-Apps/calibreweb_ynh] Server Error after installation (#66)


Hello,
after installation i get an Server 500 error.
Internal Server Error 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. Traceback (most recent call last): File "/var/www/calibreweb/vendor/flask/app.py", line 2447, in wsgi_app response = self.full_dispatch_request() File "/var/www/calibreweb/vendor/flask/app.py", line 1952, in full_dispatch_request rv = self.handle_user_exception(e) File "/var/www/calibreweb/vendor/flask/app.py", line 1821, in handle_user_exception reraise(exc_type, exc_value, tb) File "/var/www/calibreweb/vendor/flask/_compat.py", line 39, in reraise raise value File "/var/www/calibreweb/vendor/flask/app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "/var/www/calibreweb/vendor/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/var/www/calibreweb/cps/usermanagement.py", line 38, in decorated_view return login_required(func)(*args, **kwargs) File "/var/www/calibreweb/vendor/flask_login/utils.py", line 272, in decorated_view return func(*args, **kwargs) File "/var/www/calibreweb/cps/web.py", line 718, in index return render_books_list("newest", sort_param, 1, page) File "/var/www/calibreweb/cps/web.py", line 421, in render_books_list entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order) File "/var/www/calibreweb/cps/db.py", line 608, in fill_indexpage return self.fill_indexpage_with_archived_books(page, pagesize, database, db_filter, order, False, *join) File "/var/www/calibreweb/cps/db.py", line 622, in fill_indexpage_with_archived_books .join(*join, isouter=True) \ TypeError: join() missing 1 required positional argument: 'target'

First i´ve tried an installation on an raspberry pi 3b, then i get the same error. Now i try it on an thinclient and get this error. What ca i do?

**Comment by vip3r78** [comment]
Hello,
i hope this is the right one:
https://paste.yunohost.org/raw/ogutorarac

**Comment by JoshuaRL** [comment]
I'm having the same issue:
https://paste.yunohost.org/raw/ufedigomar

**Comment by Krakinou** [comment]
OK, I see that you opened an [issue](https://github.com/janeczku/calibre-web/issues/1902) on the upstream calibreweb repo.
The issue is linked to SQLAlchemy version.
According to your log, the pip3 install the 1.3.20 version, which is working, but then some dependencies in the optionnal requirement bring back the 1.4 version which broke everything.
Can you try logging as root and then use this command:
`sudo pip3 install 'SQLAlchemy==1.3.20' --force-reinstall --target /var/www/calibreweb/vendor`
You may have to adapt the path if you have multiple calibreweb instance.
This should solve the issue for your installation.

I will give it a look to know why 1.4 is installed and try to update the package.

**Comment by avephill** [comment]
> `sudo pip3 install 'SQLAlchemy==1.3.23' --force-reinstall --target /var/www/calibreweb/vendor`

I ran this code exactly, restarted the calibreweb service, and it worked! Thanks so much

**Comment by Krakinou** [comment]
Should be solved with the new update

**Comment by JoshuaRL** [comment]
This worked for me as well, for other users please remember to restart the service and if you get a 502 error like I did, restart NGINX service.
