### ISSUE TITLE
Failed to restore backup of calibreweb

### ISSUE THREAD

**Issue by lightnin** [YunoHost-Apps/calibreweb_ynh#68]
On rpi 4 from a backup restore operation over 1 24 hour period, received the following errors and calibreweb failed to restore. 
Terminal output:
https://paste.yunohost.org/raw/isatukexib

Steps to reproduce:
1. Do a full system backup via commandline yunohost backup tools.
2. Install new yunohost system on new SD card.
3. Boot system and copy backup archive via ssh to correct location as specified in backup docs.
4. Restore backup. 

All the rest of apps / system appear to have been successfully restored.

**Comment by Krakinou** [comment]
Hello
Having a look at the logs, it looks like a network error : I see a lot of 
`Cannot initiate the connection to raspbian.raspberrypi.org:80 (2a00:1098:0:80:1000:75:0:3) - connect (101: Network is unreachable)` 
errors when trying to install the dependencies.
Can you check if you can install some packages and try again?

**Comment by lightnin** [comment]
Dang - I wrongly assumed that a temporary outage wasn't the real cause, because I don't seem to get many of those. But I should have tried a second time to confirm. I tried a partial restore just now and it appears to have worked. Thanks very much for your help and sorry for the distraction!
