### ISSUE TITLE
500 Internal Server Error on Fresh Install

### ISSUE THREAD

**Issue by avephill** [YunoHost-Apps/calibreweb_ynh#69]
## Hardware
* Running Yunohost 4.1.7.4 on a raspberry pi 4
* Calibre-web 0.96.10

## Reproducing the problem
1. Install Calibre-web with settings: language = english; Upload Books = yes; Allow Access to All Users = yes;
2. navigate to subdomain that it was installed on
3. enter yunohost user credentials into yunohost login
4. Receive "500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

My system monitor would suggest that the server was not overloaded

## Log file
https://paste.yunohost.org/qonubawuka

**Comment by Krakinou** [comment]
Duplicate from #66
