### ISSUE TITLE
upgrade failed

### ISSUE THREAD

**Issue by MX10-AC2N** [YunoHost-Apps/calibreweb_ynh#82]
Hello everyone and especially @Krakinou 
This morning, I try to update calibreweb but it was not successful, there was a problem creating the backup.
Here is the copy of the log => https://paste.yunohost.org/raw/bozaqekoru

I specify that I also entered the command given in the README.md
 " By default, Yunohost backup process will backup Calibreweb library. You may deactivate backup of the library with "
```
yunohost app setting calibreweb do_not_backup_data -v 1 
```

**Comment by Krakinou** [comment]
Hello,
This is very strange indeed : Can you try following command on the command line (maybe with sudo): 
`sqlite3 /var/www/calibreweb/app.db 'SELECT config_calibre_dir FROM settings WHERE ID=1'`
This should give back the folder where is located your library according to the settings from calibre-web.
Do you have any special settings? Using google drive maybe?

**Comment by MX10-AC2N** [comment]
Hi and thank you @Krakinou
I am using calibreweb with my library on an external drive (maybe the problem came from there ..)
I used the command that you indicated to me that does not return any particular message, I am relaunching the upgrade but it still bugs ..
Here is the copy of the log => https://paste.yunohost.org/raw/irosusawav

**Comment by MX10-AC2N** [comment]
https://paste.yunohost.org/raw/suyolureke => log of backup create failed..

**Comment by MX10-AC2N** [comment]
I also just noticed that I can no longer access a calibreweb via the local IP address, only the access via the domain name remains accessible .. Strange because before I succeeded very well in connecting myself locally (surely a problems with the yunohost firewall ...)

**Comment by Krakinou** [comment]
can you give me the output of the following command:
`sqlite3 /var/www/calibreweb/app.db "SELECT * from settings WHERE ID=1"`
Do you see the path where the library is stored in the calibreweb settings?

**Comment by MX10-AC2N** [comment]
Thank @Krakinou 
```
os:~# sqlite3 /var/www/calibreweb/app.db "SELECT * from settings WHERE ID=1"
1|mail.example.org|25|0|mail@example.com|mypassword|automailer <mail@example.com>|26214400||8083|8083|||Calibre-Web|60|4|0|0|^(A|The|An|Der|Die|Das|Den|Ein|Eine|Einen|Dem|Des|Einem|Eines)\s+||0|20|/var/log/calibreweb/calibreweb.log|1|/var/log/calibreweb/calibreweb-access.log|1|0|0|0|0|0|262143||||0|||0||{}|0|||0|1|0|localhost|389|0|cn=admin,dc=example,dc=org||0||||dc=yunohost,dc=org|(&(objectClass=posixAccount)(permission=cn=calibreweb.main,ou=permission,dc=yunohost,dc=org)(uid=%s))||1|(&(objectClass=posixGroup)(permission=cn=%s.main,ou=permission,dc=yunohost,dc=org))|memberUid|calibreweb|||||doc,mobi,mp3,ogg,txt,cbz,flac,djvu,wav,fb2,lit,docx,cbt,opus,azw,m4a,pdf,cbr,html,epub,odt,rtf,mp4,prc,kepub,azw3,m4b|0||0|0|{}
```
And Yes I can see the path where my library is stored in the calibreweb settings..

**Comment by Krakinou** [comment]
oO
This is really really strange: the field where the library is stored in the database is empty... So the app shouldn't work at all... I'm quite confused by this one :). But you have twice the info of the port (where it's written 8083). Something went wild somewhere...

Can you try this: try modifying the folder in calibre-web settings (even to put back the same value) and save the settings, so that it update the database again? and then check again?

**Comment by MX10-AC2N** [comment]
Hello and thank you @Krakinou that worked. I was able to update after putting the path to the media library back in the settings, it is however exactly the same as what there was already, well it works. .
Here is what 
sqlite3 /var/www/calibreweb/app.db gives me "SELECT * from settings WHERE ID = 1"
```
1|mail.example.org|25|0|mail@example.com|mypassword|automailer <mail@example.com>|26214400|/media/ac2n-cloud/eBook|8083|8083|||Calibre-Web|60|4|0|0|^(A|The|An|Der|Die|Das|Den|Ein|Eine|Einen|Dem|Des|Einem|Eines)\s+||0|20|/var/log/calibreweb/calibreweb.log|1|/var/log/calibreweb/calibreweb-access.log|1|0|0|0|0|0|262143||||0|||0||{}|0|||0|1|0|localhost|389|0|cn=admin,dc=example,dc=org||0||||dc=yunohost,dc=org|(&(objectClass=posixAccount)(permission=cn=calibreweb.main,ou=permission,dc=yunohost,dc=org)(uid=%s))||1|(&(objectClass=posixGroup)(permission=cn=%s.main,ou=permission,dc=yunohost,dc=org))|memberUid|calibreweb|||||doc,mobi,mp3,ogg,txt,cbz,flac,djvu,wav,fb2,lit,docx,cbt,opus,azw,m4a,pdf,cbr,html,epub,odt,rtf,mp4,prc,kepub,azw3,m4b|0||0|0|{}
```
And I did not find direct access via IP (192.168.1.xxx:8083)
is there a particular command to regain local access ..?
Thanks again..

**Comment by Krakinou** [comment]
Hello,
Glad it worked :)
For the access via the IP, I don't know as I'm always using domain name: you should ask on the yunohost forum.
