### ISSUE TITLE
Installation failed on Lime 2

### ISSUE THREAD

**Issue by lapor-kris** [YunoHost-Apps/calibreweb_ynh#83]
### Describe the bug

I tried to install the Calibre-web on Yunohost and it failed.

### Context

- Hardware: Olinuxino Lime 2
- YunoHost version: 4.2.6.1 (stable)
- I have access to my server: Through SSH and through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 0.96.12~ynh2

### Steps to reproduce

   1. Select Calibre-web from the apps for installation
   2. Set it to sub-domain, change language to EN
   3. Set "Do you want to allow uploading of books?" to yes
   4. Click "Install" and wait.
   5. See error

### Expected behavior

It should install without errors.

### Logs

https://paste.yunohost.org/raw/ehoqucinig

**Comment by Krakinou** [comment]
Hi,
This is a dependency error I think: can you try
`sudo apt install libxml2-dev libxslt-dev` and then run the install again?
If this work, I will add them into the dependency of the app.

**Comment by lapor-kris** [comment]
Hey,
I installed the dependency and I tried the installation again. Not it is stuck at "Installing pip requirements..." for around 30 min. I think it will not continue. Or it needs so much time to install pip?
BTW, is there a way to Cancel (stop) the running installation in the webadmin interface?
Thanks

**Comment by Krakinou** [comment]
Pip package may take a long time to install as it seems that it's compiling stuff and others, so depending on your hardware, and what is already installed, it may take a while.
I don't know about the yunohost command, you may ask on the forum : I never encountered such a case.
Maybe you can check with top/htop and try to kill it?
Do you get access to the corresponding log in `/var/log/yunohost/categories/operation/`?

**Comment by lapor-kris** [comment]
I had to rebuild it. I'm still learning how to work with it and what can do this little beast :)
I will check it again and give it a try.
