### ISSUE TITLE
Error: LDAP Member User Filter needs to Have One "%s" Format Identifier

### ISSUE THREAD

**Issue by psharma04** [YunoHost-Apps/calibreweb_ynh#84]
**How to post a meaningful bug report**
1. *Read this whole template first.*
2. *Determine if you are on the right place:*
   - *If you were performing an action on the app from the webadmin or the CLI (install, update, backup, restore, change_url...), you are on the right place!*
   - *Otherwise, the issue may be due to the app itself. Refer to its documentation or repository for help.*
   - *When in doubt, post here and we will figure it out together.*
3. *Delete the italic comments as you write over them below, and remove this guide.*
--- 

### Describe the bug

Can't access the Calibre-web interface, stuck on the /basicconfig page despite an already set up instance with nearly 2GB of books.

### Context

- Hardware: Linode Nanode VPS
- YunoHost version: 4.2.7
- I have access to my server: SSH, YunoHost panel, VNC to TTY.
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No
  - If yes, please explain:
- Using, or trying to install package version/branch: 
- If upgrading, current package version: 0.96.12~ynh2

### Steps to reproduce
   1. In the Webadmin, go to System Update
   2. Select Update All
   3. Once the update completes, navigate to the Calibre-web page.
   4. Observe the error.

### Expected behavior
I expect to pick up where I left off with the web interface, maybe log in again, but not have a completely broken Calibre instance.

### Logs
N/A, Yunohost has no errors.
![image](https://user-images.githubusercontent.com/22587474/129540353-878aa597-3b8a-4397-b9b3-e28f59db354e.png)

**Comment by Krakinou** [comment]
Hello
If I understand correctly, you updated from 0.96.12~ynh1 to 0.96.12~ynh2 and then you get this error message?
The purpose of this update was to change some LDAP settings to have a working user automatic creation, but it shouldn't have change anything in the LDAP Member user filter. 
Did you change some settings regarding LDAP in calibreweb?
Can you post the results of the 2 following command lines :
````
sqlite3 /var/www/calibreweb/app.db "SELECT config_ldap_group_object_filter FROM settings"
sqlite3 /var/www/calibreweb/app.db "SELECT config_ldap_user_object FROM settings"
````

**Comment by Krakinou** [comment]
Also, if you still have it, can you post the log of the upgrade? You may find it in the admin panel of yunohost, under tools/log

**Comment by Ekpu** [comment]
Hallo,
I got the same problem.
Upgraded calibre-web to 0.96.13 ynh1 and getting the error `LDAP bind_user: simple_bind() argument 1 must be str or None, not dict` on login.
Reverted to the preupgrade backup and in trying to set the path in basicconfig I got the same error as psharma04.
Here is the output of the two commands (on 0.96.13 ynh1):
`sqlite3 /var/www/calibreweb/app.db "SELECT config_ldap_group_object_filter FROM settings"
(&(objectClass=posixGroup)(cn=%s.main))`

`sqlite3 /var/www/calibreweb/app.db "SELECT config_ldap_user_object FROM settings"
(&(objectClass=posixAccount)(permission=cn=calibreweb.main,ou=permission,dc=yunohost,dc=org)(uid=%s))`

**Comment by Ekpu** [comment]
Hello,
so I did a reinstall auf calibreweb from the yunohost webadminpanel and it is working again.
Not the ideal solution If you have a complex configuration but in my case I just had to set the correct path for my database.
